-- Ensure Harpoon is available
local harpoon = require("harpoon")

-- Setup Harpoon
harpoon:setup()

-- Keymaps with <leader>a prefix
vim.keymap.set("n", "<leader>aa", function()
  harpoon:list():add()
end, { desc = "Add file to Harpoon" })
vim.keymap.set("n", "<leader>am", function()
  harpoon.ui:toggle_quick_menu(harpoon:list())
end, { desc = "Toggle Harpoon menu" })
vim.keymap.set("n", "<leader>a1", function()
  harpoon:list():select(1)
end, { desc = "Jump to Harpoon file 1" })
vim.keymap.set("n", "<leader>a2", function()
  harpoon:list():select(2)
end, { desc = "Jump to Harpoon file 2" })
vim.keymap.set("n", "<leader>a3", function()
  harpoon:list():select(3)
end, { desc = "Jump to Harpoon file 3" })
vim.keymap.set("n", "<leader>a4", function()
  harpoon:list():select(4)
end, { desc = "Jump to Harpoon file 4" })
vim.keymap.set("n", "<leader>ap", function()
  harpoon:list():prev()
end, { desc = "Harpoon previous file" })
vim.keymap.set("n", "<leader>an", function()
  harpoon:list():next()
end, { desc = "Harpoon next file" })
vim.keymap.set("n", "<leader>ar", function()
  harpoon:list():remove()
end, { desc = "Remove current file from Harpoon" })
